#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ID_SHARED_NANO_SECONDS 1
#define ID_SHARED_SECONDS 2
#define ID_SEM_CRITICAL 3
#define ID_SHARED_PCB 4
#define ID_SHARED_PAGE 5
#define ID_SHARED_FRAME 6
#define ID_MSG_REQUEST 7
#define NANO_PER_SECOND 1000000000
#define MAX_PROCESSES 18
#define MAX_PAGES 32
#define MAX_REAL_SECONDS 2
#define NUM_PAGE_FRAMES 256
#define KILO_PER_BYTE 1000
#define MAX_COMPLTETED_PROCESSES 100
#define MAX_SYSTEM_SECONDS 3

#endif
